name: testing

on:
  push:
    branches: [ ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo mysql mbstring bcmath zip iconv
      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist
      - name: Cache composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-build-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-build-
      - name: Run tests
        run: |
          ./vendor/bin/sail php artisan test
