name: Run Laravel Sail Tests

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: sail
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install docker-compose -y

    - name: Build and start Sail
      run: |
        cp .env.example .env
        composer install --no-interaction --prefer-dist
        ./vendor/bin/sail up -d
      env:
        MYSQL_PASSWORD: password

    - name: Run Tests
      run: ./vendor/bin/sail test
